### PR TITLE
Drop django < 1.8

### PR DESCRIPTION
**Pull request by saily**
This merge request fixes several problems with test setup:

- I've updated testcases to use [PhantomJS](http://phantomjs.org) instead of google webdriver which makes tests more stable and faster.
- Switch to `pytest` and `pytest-selenium` which basically supports running on any webdriver which is supported by Selenium.
- Use tox to setup test environment
- Drop support for Django < 1.8
- Support Django 1.8, 1.9, 1.10 in tests
- Support Python 2.7, 3.3, 3.4, 3.5, 3.6 in tests, see [Django supported python versions](https://docs.djangoproject.com/en/1.9/faq/install/#what-python-version-can-i-use-with-django).
- Adapt new template settings according to [Django upgrade guide](https://docs.djangoproject.com/en/1.9/ref/templates/upgrading)
- Extract changelog and move it to `Changelog.rst`

Will close #23.

### CODE REVIEW

**Comment by saily** [comment]
@centralniak can you please review

**Comment by saily** [comment]
@centralniak i'm requesting access to do some more maintenance here and release it on pypi. My pypi username is `saily`.

**Comment by centralniak** [comment]
Thank you @saily - I appreciate your offer. I'll get back to you in due course.

**Comment by saily** [comment]
hi @centralniak, kindly asking for merge.

**Comment by centralniak** [comment]
Before we merge we need to find out why builds in Travis hang. Otherwise, I think I agree with the changes you did.

**Comment by saily** [comment]
@centralniak travis build hang issue fixed, i'm using a better test-matrix now. this is ready to merge now.

**Comment by saily** [comment]
@centralniak did you already have time to look into it?

**Comment by do3cc** [comment]
I second @saily, maybe this ticket got lost?

**Comment by saily** [comment]
@do3cc what do you mean? i think @centralniak has to look into that and decide how to continue.

**Comment by centralniak** [comment]
Sorry, @saily @do3cc I've been so ignorant about this ticket.

Yes, this is great. I'm mergin' now.

A pypi issue would be good I suppose?

**Comment by centralniak** [comment]
This has been released as version `2.0.0`, as it's not backwards compatible.

**Pull request merged**
