### PR TITLE
Return '' if context has no request, fixes #37

### LINKED ISSUE #37: KeyError when an exception is raised
When an exception is raised and the tag is rendered the request is not in context. Warning is displayed but I get a KeyError because of the code doesn't return or raise something.

### PR DESCRIPTION
**Pull request by khink**
This should fix #37

### CODE REVIEW

**Comment by khink** [comment]
@centralniak The failing tests are not due to this PR. The first failing test's message is "Unsupported Python version - This version of Django requires Python 3.5, but you're trying to install it on Python 2.7.". 

Also, Django <1.11 and Python3.4 are unsupported (don't receive security updates), so i think these can be removed from the test matrix altogether.

I think the test matrix could use an update. Do you want me to include that in this PR?

**Comment by centralniak** [comment]
@khink Thanks for a PR.

I agree, it looks like the failures have nothing to do with your changes and the Travis matrix is in need of a rewrite/update.

If you can, please include it either in this PR or a separate one.

Once this MR is passing and merged, I'll update the project on pypi.

**Comment by centralniak** [comment]
@khink #51 merged, do you want to rebase this one?

**Comment by khink** [comment]
Rebased @centralniak !

**Comment by centralniak** [comment]
I'll make a release today.

**Comment by centralniak** [comment]
Released as 2.0.2.

**Pull request merged**
